wandb_version: 1

trainer_select:
  desc: null
  value: trainer_fmri_img
model_name:
  desc: null
  value: MindBrige_image_only_mixco_loss
data_path:
  desc: null
  value: /media/SSD_1_2T/xt/data/natural-scenes-dataset
subj_list:
  desc: null
  value:
  - 1
  - 2
  - 5
  - 7
subj_source:
  desc: null
  value:
  - 1
subj_target:
  desc: null
  value:
  - 1
adapting:
  desc: null
  value: false
batch_size:
  desc: null
  value: 100
val_batch_size:
  desc: null
  value: 50
clip_variant:
  desc: null
  value: ViT-B/32
wandb_log:
  desc: null
  value: true
wandb_project:
  desc: null
  value: MindBrige_image_only_mixco_loss
resume:
  desc: null
  value: false
resume_id:
  desc: null
  value: null
load_from:
  desc: null
  value: null
norm_embs:
  desc: null
  value: true
use_image_aug:
  desc: null
  value: true
num_epochs:
  desc: null
  value: 150
lr_scheduler_type:
  desc: null
  value: cycle
ckpt_interval:
  desc: null
  value: 1
eval_interval:
  desc: null
  value: 1
h_size:
  desc: null
  value: 2048
n_blocks:
  desc: null
  value: 4
seed:
  desc: null
  value: 42
num_workers:
  desc: null
  value: 2
max_lr:
  desc: null
  value: 0.0015
mixup_pct:
  desc: null
  value: 0.2
pool_num:
  desc: null
  value: 8192
pool_type:
  desc: null
  value: max
mse_mult:
  desc: null
  value: 100000.0
mae_mult:
  desc: null
  value: 100.0
cos_mult:
  desc: null
  value: 10.0
ssim_mult:
  desc: null
  value: 10000.0
rec_mult:
  desc: null
  value: 1.0
cyc_mult:
  desc: null
  value: 1.0
nce_mult:
  desc: null
  value: 1.0
clip_mult:
  desc: null
  value: 1.0
length:
  desc: null
  value: null
autoencoder_name:
  desc: null
  value: null
subj_load:
  desc: null
  value: null
subj_test:
  desc: null
  value: 1
samples:
  desc: null
  value: null
img2img_strength:
  desc: null
  value: 0.85
guidance_scale:
  desc: null
  value: 3.5
num_inference_steps:
  desc: null
  value: 20
recons_per_sample:
  desc: null
  value: 16
plotting:
  desc: null
  value: true
diffusion_cache_dir:
  desc: null
  value: ../weights
gpu_id:
  desc: null
  value: 0
ckpt_from:
  desc: null
  value: last
text_image_ratio:
  desc: null
  value: 0.5
test_start:
  desc: null
  value: 0
test_end:
  desc: null
  value: null
only_embeddings:
  desc: null
  value: false
synthesis:
  desc: null
  value: false
verbose:
  desc: null
  value: true
results_path:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.42.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721645486.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 79
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 79
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.14
      5: 0.16.6
      6: 4.42.4
      8:
      - 5
      13: linux-x86_64
